// INSTRUCTION BYTECODES (byte is signed )
const int IADD    = 1;
const int ISUB    = 2; 
const int IMUL    = 3;
const int IDIV    = 4;
const int ILT     = 5; 
const int IEQ     = 6; 
const int BR      = 7;  // branch
const int BRT     = 8;  // branch if true
const int BRF     = 9;  // branch if false
const int ICONST  = 10; // push constant integer
const int LOAD    = 11; // load from local
const int GLOAD   = 12; // load from global
const int STORE   = 13; // store in local
const int GSTORE  = 14; // store in global
const int PRINT   = 15; // print stack top
const int PRINTLN = 16;
const int POP     = 17; // throw away top of stack
const int HALT    = 18; // stop execution